#!/bin/bash

if command -v gnome-terminal 1>/dev/null; then
    gnome-terminal --tab --working-directory=`pwd` -- bash -c "/bin/bash -c 'python3 -m http.server 8000'; exec bash"
else
    python3 -m http.server 8000 &
fi

sleep 1

# For some reason chromium isn't producing console.log output

# if command -v chromium 1>/dev/null; then
#     chromium http://localhost:8000
if command -v google-chrome 1>/dev/null; then
    google-chrome http://localhost:8000
else
    firefox "http://localhost:8000"
fi
